version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "7070:7070"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: yolo-app-network
